version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: dorecepty_db
    environment:
      POSTGRES_DB: dorecepty
      POSTGRES_USER: dorecepty_user
      POSTGRES_PASSWORD: dorecepty_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
